export const SET_CURRENT_WEATHER = 'SET_CURRENT_WEATHER';
export const SET_CURRENT_FORECAST = 'SET_CURRENT_FORECAST';
export const DELETE_CITY = 'DELETE_CITY ';
export const CURRENT_SEARCH_CITY = 'CURRENT_SEARCH_CITY';